#!/bin/bash
#
# Perform interactive install of SaltStack

__ScriptName="salt_install"
install_type=""
separator="\033[35m===>\033[0m"

usage() {
  cat << EOT

  Usage :  ${__ScriptName} [options] <install-type>

  Installation types:
    - salt-master
    - salt-minion

  Examples:
    - ${__ScriptName} -r salt-master

  Options:
  -h  Display this message
  -r  Set role

EOT
}

while getopts "hr:" option
do
  case "${option}" in
    h)
      usage
      exit 0
      ;;
    r)
      if [[ $OPTARG == "salt-master" ]] || [[ $OPTARG == "salt-minion" ]]; then
        install_type="${OPTARG}"
        break
      else
        echo "Role must be 'salt-master' or 'salt-minion'"
        exit 1
      fi
      ;;
  esac
done

echo -e "${separator} add SaltStack PPA"

if grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/* | grep saltstack > /dev/null; then
  echo "SaltStack PPA is already in sources list"
else
  add-apt-repository -y ppa:saltstack/salt
fi

apt-get update

echo -e "${separator} install ${install_type}"

apt-get install ${install_type} -y

echo -e "${separator} add ${install_type} service to update-rc.d"

update-rc.d ${install_type} defaults

echo -e "${separator} start ${install_type}"

if ps ax | grep -v grep | grep ${install_type} > /dev/null; then
  echo "${install_type} is running"
else
  echo "starting ${install_type}"
  service ${install_type} start
fi
